language: ruby
rvm:
  - 2.1
script:
  - bundle exec jekyll build --config _config_dev.yml
  - bundle exec htmlproof ./_site --only-4xx --check-html --disable-external
# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
